- name: APT update the system
  apt:
    upgrade: true
    update_cache: true

- name: Ensure basic packages are installed
  apt:
    name:
      - ansible
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - htop
      - jq
      - lsb-release
      - neovim
      - nginx
      - qemu-guest-agent
      - ufw
      - vim
      - wget
      - zsh
    state: present
